### PR TITLE
Change event priorities to MONITOR

### LINKED ISSUE #321: Wrong priorities for events
### Description

Deobfuscation does not work if another plugin changes blacklist to EntityExplodeEvent with lower priority than Orebfuscator

### Reproduction Steps

change event.blocklist() in priority lower than `NORMAL`

```
@EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onEntityExplode(EntityExplodeEvent event) {
        event.blocklist().addAll(..nearby blocks...)
    }
```
image

### Expected Behaviour

All nearby blocks must be deobfuscated

### Orebfuscator Dump

Purpur 1.20.1
https://github.com/Imprex-Development/orebfuscator/commit/56e2f23f8848bc6fa4199a35bb4ebe22c523e628

### Extra Details

_No response_

### PR DESCRIPTION
**Pull request by kforbro**
## Description
Event priorities have been changed to MONITOR, and ignoring canceled events is also enabled for compatibility with other plugins that change events with a lower priority.

## Related Issue
closes #321 

## Motivation and Context

#321 

## How Has This Been Tested?
Not tested, since I can't build the jar at the moment, but it should work fine, since there are no major changes in the code.

## Types of Changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

File: orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/proximity/ProximityDirectorThread.java [hunk 1]
```diff
@@ -12,6 +12,7 @@
 import org.bukkit.Bukkit;
 import org.bukkit.entity.Player;
 import org.bukkit.event.EventHandler;
+import org.bukkit.event.EventPriority;
```
Comment (Ingrim4) [inline orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/proximity/ProximityDirectorThread.java]: please remove unused imports

File: orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/obfuscation/DeobfuscationListener.java [hunk 2]
```diff
@@ -40,49 +41,49 @@ private DeobfuscationListener(Orebfuscator orebfuscator, DeobfuscationWorker deo
 		this.deobfuscationWorker = deobfuscationWorker;
 	}
 
-	@EventHandler
+	@EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
```
Comment (Ingrim4) [inline orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/obfuscation/DeobfuscationListener.java]: Basically ok, but I would prefer `EventPriority.HIGH` so that other plugins still have the option to ignore Orebfusactor for whatever reason

**Review by Ingrim4 — CHANGES_REQUESTED** [review]

File: orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/obfuscation/DeobfuscationListener.java (hunk 2 above)
Comment (kforbro) [reply orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/obfuscation/DeobfuscationListener.java]: > Basically ok, but I would prefer `EventPriority.HIGH` so that other plugins still have the option to ignore Orebfusactor for whatever reason

What do you mean by ignoring Orebfuscator? Via API in HIGHEST priority?

Comment (Ingrim4) [reply orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/obfuscation/DeobfuscationListener.java]: I would prefer `EventPriority.HIGH` because if a plugin for whatever reason wants to edit a event and hide the change from other plugins such a Orebfuscator their would still be `EventPriority.HIGHEST` and `EventPriority.MONITOR`. I just don't see the point in using anything different then `EventPriority.NORMAL` or `EventPriority.HIGH` here since that leaves other plugins with plenty of options the be execute before or after Orebfuscator if they desire to.

File: orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/proximity/ProximityDirectorThread.java (hunk 1 above)
Comment (kforbro) [reply orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/proximity/ProximityDirectorThread.java]: there are no unused imports. EventPriority used in @EventHandler

Comment (Ingrim4) [reply orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/proximity/ProximityDirectorThread.java]: No you didn't specify an EventPriority anywhere in this class which makes this an unused import. Their also shouldn't be an EventPriority on the PlayerJoinEvent since their is no need to change anything here.

Comment (kforbro) [reply orebfuscator-plugin/src/main/java/net/imprex/orebfuscator/proximity/ProximityDirectorThread.java]: oh, didn't notice this file

**Review by Ingrim4 — APPROVED** [review]
